### ISSUE TITLE
support vcs/verdi

### ISSUE THREAD

**Issue by bingoshu** [dpretet/svut#22]
i hope this python script can support   vcs/verdi

**Comment by dpretet** [comment]
Hi,

can you give a try to this branch 'issue22':

https://github.com/dpretet/svut/tree/issue22

Best,
Damien

**Comment by bingoshu** [comment]
Hi,


I'm on holiday to celebrate the Chinese New Year，i will try in the week after next.


think you.


Best Regards
bing




At 2022-01-25 15:52:23, "Damien Pretet" ***@***.***> wrote:

Hi,

can you give a try to this branch 'issue22':

https://github.com/dpretet/svut/tree/issue22

Best,
Damien

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dpretet** [comment]
Hello,

Is everything work correctly as you expected?

Damien
